# Generated by Django 4.1.7 on 2023-10-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_appointment_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='details_crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
