# Generated by Django 4.1.7 on 2023-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_details_crud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_crud',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
