# Generated by Django 4.1.7 on 2023-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_upload_alter_details_crud_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=50)),
                ('RollNo', models.CharField(max_length=10)),
                ('Mobile', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Father', models.CharField(max_length=100)),
                ('Mother', models.CharField(max_length=100)),
                ('ParentMobile', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=11)),
                ('Mobile', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
