# Generated by Django 4.1.7 on 2023-10-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_studentdata_teacherdata_upload_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
