# Generated by Django 4.1.7 on 2023-11-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('fame', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=50)),
                ('RollNo', models.CharField(max_length=10)),
                ('Mobile', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Father', models.CharField(max_length=100)),
                ('Mother', models.CharField(max_length=100)),
                ('ParentMobile', models.PositiveBigIntegerField()),
            ],
        ),
        
    ]
